/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.jonathangiles.tools.jed.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum SourceType implements org.apache.avro.generic.GenericEnumSymbol<SourceType> {
  EVENTHUBS, KAFKA, KINESIS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SourceType\",\"namespace\":\"net.jonathangiles.tools.jed.avro.model\",\"symbols\":[\"EVENTHUBS\",\"KAFKA\",\"KINESIS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
